-- =============================================================================
-- MDP PLC Hybrid Table Setup
-- Point lookup optimization for CONSENSUS_UNIQUE_IDENTIFIER via B-tree PK
-- Target: sub-50ms point lookup latency (expected: sub-10ms warm)
-- =============================================================================

USE SCHEMA ISRG_D3_DB.CURATED;

-- Create Hybrid Table with explicit schema (required for CTAS)
-- Primary key on CONSENSUS_UNIQUE_IDENTIFIER provides native B-tree index
-- No clustering key needed - hybrid tables are ordered by PK natively
CREATE OR REPLACE HYBRID TABLE ISRG_D3_DB.CURATED.MDP_PLC_ST_HYBRID (
  CONSENSUS_UNIQUE_IDENTIFIER NUMBER(19,0) NOT NULL PRIMARY KEY,
  ALL_OBSERVED_UIDS VARIANT,
  LOWER_TIER_IDS VARIANT,
  UPPER_TIER_IDS VARIANT,
  LOWER_SERIAL_NUMBERS VARIANT,
  UPPER_SERIAL_NUMBERS VARIANT,
  LOWER_SERIAL_NUMBERS_DETAIL VARIANT,
  UPPER_SERIAL_NUMBERS_DETAIL VARIANT,
  FINAL_LOWER_SERIAL_NUMBER VARCHAR(16777216),
  FINAL_UPPER_SERIAL_NUMBER VARCHAR(16777216),
  LOWER_PART_NUMBERS VARIANT,
  LOWER_PARTCLASS VARCHAR(16777216),
  UPPER_PART_NUMBERS VARIANT,
  UPPER_PARTCLASS VARCHAR(16777216),
  LOWER_WORK_ORDER_NUMBERS VARIANT,
  UPPER_WORK_ORDER_NUMBERS VARIANT,
  WORK_ORDERS_DETAIL VARIANT,
  SERIAL_UID_RESOLUTION VARIANT,
  LOWER_TIER_COUNT NUMBER(38,0),
  UPPER_TIER_COUNT NUMBER(38,0),
  CONSENSUS_CONFIDENCE FLOAT,
  LINK_TYPE VARCHAR(16777216),
  DEDUP_STATUS VARCHAR(16777216),
  LINKAGE_LAST_UPDATED TIMESTAMP_TZ(9)
)
AS SELECT * FROM ISRG_D3_DB.CURATED.MDP_PLC_ST;

-- Verify row count
SELECT COUNT(*) AS row_count FROM ISRG_D3_DB.CURATED.MDP_PLC_ST_HYBRID;

-- Verify hybrid table status
SHOW HYBRID TABLES LIKE 'MDP_PLC_ST_HYBRID' IN SCHEMA ISRG_D3_DB.CURATED;

-- Test point lookups (uses any standard warehouse - no dedicated WH needed)
SELECT * 
FROM ISRG_D3_DB.CURATED.MDP_PLC_ST_HYBRID
WHERE CONSENSUS_UNIQUE_IDENTIFIER = 8146597745;

SELECT CONSENSUS_UNIQUE_IDENTIFIER
FROM ISRG_D3_DB.CURATED.MDP_PLC_ST_HYBRID
WHERE CONSENSUS_UNIQUE_IDENTIFIER = 9223371420611404425;

SELECT CONSENSUS_UNIQUE_IDENTIFIER
FROM ISRG_D3_DB.CURATED.MDP_PLC_ST_HYBRID
WHERE CONSENSUS_UNIQUE_IDENTIFIER = 8146597745;
-- =============================================================================
-- Cleanup (run when done with POC)
-- =============================================================================
-- DROP TABLE IF EXISTS ISRG_D3_DB.CURATED.MDP_PLC_ST_HYBRID;
